Repository Dollar-Dynasty/finance-app, pull requests merged in 2024-02, with the labels that each got.

#34 chore: added loginPage html, css and js
  public/css/loginPage.css
  public/js/loginPage.js
  public/loginPage.html
Labels: enhancement, Styling

#17 feat:create a budget form
  public/budgetCreation.html
  public/js/budgetCreation.js
Labels: enhancement

#40 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#44 fix:goal creations form
  public/goalCreation.html
  public/js/goalCreation.js
Labels: bug

#46 feat: added APIroutes and viewRoutes for register and login pages
  app.js
  package-lock.json
  package.json
  routes/apiRoutes.js
  routes/login.route.js
  routes/viewRoutes.js
Labels: enhancement

#41 Integrated Firebase Authentication
  .gitignore
  app.js
  config/dbConnection.js
  models/loginModel.js
  models/userModel.js
  package-lock.json
  package.json
  routes/apiRoutes.js
  routes/viewRoutes.js
  views/pages/index.ejs
  views/pages/login.ejs
  views/pages/register.ejs
Labels: enhancement

#54 bugfix: changed title to Dollar Dynasty
  views/pages/index.ejs
Labels: good first issue

#58 feat: converted goalCreation.html to ejs
  routes/viewRoutes.js
  views/js/goalCreation.js
  views/pages/goalCreation.ejs
Labels: enhancement

#55 feature: Created Welcome Page
  routes/viewRoutes.js
  views/pages/welcome.ejs
Labels: enhancement

#56 feat: converted BudgetCreation to ejs
  routes/viewRoutes.js
  views/js/budgetCreation.js
  views/pages/budgetCreation.ejs
Labels: enhancement

#62 added categorycreation.ejs file
  views/pages/categoryCreation.ejs
Labels: enhancement, good first issue

#61 Feature/budget to db
  models/budgetModel.js
  routes/apiRoutes.js
  views/pages/budgetCreation.ejs
Labels: enhancement

#64 feat: Added Goal Adding Functionality
  models/goalsModel.js
  routes/apiRoutes.js
  views/js/goalCreation.js
  views/pages/goalCreation.ejs
Labels: enhancement

#65 feat: Added flow for goal and budget after register
  routes/apiRoutes.js
Labels: enhancement

#66 feature: Added plotly with dummy data
  package.json
  routes/apiRoutes.js
  views/js/index.js
  views/pages/index.ejs
  views/partials/head.ejs
Labels: enhancement

#67 feature: Added Logout button
  views/partials/visitorHeader.ejs
Labels: enhancement

#69 Add Pie Chart Data-Visualization | Update Codebase Structure, Formatting, and MVP Styling
  app.js
  archive/category-form-old.ejs
  archive/login-form-unused.ejs
  config/db-connection.js
  controller/budget-controller.js
  controller/login.controller.js
  controller/userController.js
  models/budget-model.js
  models/budgetModel.js
  models/dashboard-model.js
  models/goals-model.js
  models/login-model.js
  models/user-model.js
  public/loginPage.html
  routes/budget-routes.js
  routes/user-account-routes.js
  routes/view-routes.js
  routes/viewRoutes.js
  views/pages/budget-form.ejs
  views/pages/budgetCreation.ejs
  views/pages/categoryCreation.ejs
  views/pages/goalCreation.ejs
  views/pages/goals-form.ejs
  views/pages/index.ejs
  views/pages/login-form.ejs
  views/pages/login.ejs
  views/pages/registration-form.ejs
  views/pages/user-dashboard.ejs
  views/pages/welcome.ejs
  views/partials/addCategory.ejs
  views/partials/footer.ejs
  views/partials/head.ejs
  views/partials/landing-header.ejs
  views/script/budgetCreation.js
  views/script/goalsForm.js
  views/script/index.js
  views/script/loginForm.js
  views/script/userDashboard.js
  views/styles/loginPage.css
  views/styles/partials/footer.css
Labels: enhancement

#73 feat: Added budgets api and set budget to dynamic
  routes/user-account-routes.js
  views/pages/user-dashboard.ejs
  views/script/userDashboard.js
Labels: bug, enhancement

#76 bugfix: Budget now successfully displays
  models/budget-model.js
  routes/user-account-routes.js
  views/pages/budget-form.ejs
Labels: bug

#77 chore: Added display if there is no budget or goals
  views/script/userDashboard.js
Labels: enhancement

#79 Feature: Displayed budget total
  views/pages/user-dashboard.ejs
  views/script/userDashboard.js
Labels: enhancement

#80 Revert "Feature: Displayed budget total"
  views/pages/user-dashboard.ejs
  views/script/userDashboard.js
Labels: bug

#84 chore: added budgetPage.js and goalsPage.js
  views/pages/budget-page.ejs
  views/pages/goals-page.ejs
  views/script/budgetPage.js
  views/script/goalsPage.js
Labels: bug

#83 Add total monthly income to dashboard
  views/pages/user-dashboard.ejs
  views/script/userDashboard.js
Labels: enhancement

#87 Feature/dashboard display total budget
  views/pages/user-dashboard.ejs
  views/script/userDashboard.js
Labels: enhancement

#86 chore: Added budget description
  views/pages/budget-page.ejs
  views/pages/goals-page.ejs
  views/script/budgetPage.js
  views/script/goalsPage.js
Labels: enhancement, Styling

#92 Update issue templates
  .github/ISSUE_TEMPLATE/bug-fix-request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/styling-request.md
Labels: documentation

#89 Feature/delete budget
  routes/user-account-routes.js
  views/pages/budget-page.ejs
  views/pages/budgetCreation.ejs
  views/pages/user-dashboard.ejs
  views/script/budgetPage.js
  views/script/userDashboard.js
  views/styles/styles.css
  views/styles/styles.scss
Labels: enhancement

#100 Displayed Goal and Saving stats
  public/js/userDashboard.js
  views/pages/logged-in-user/user-dashboard.ejs
Labels: enhancement

#105 chore: add multiple goals feature & styling
  views/pages/index.ejs
  views/pages/user-dashboard.ejs
  views/script/userDashboard.js
  views/styles/_mixins.scss
  views/styles/styles.css
  views/styles/styles.scss
Labels: bug, enhancement

#106 changes about page and contact page
  views/pages/contact-page.ejs
  views/pages/index.ejs
Labels: bug, enhancement

#111 Change submit buttion to log in
  views/pages/login-form.ejs
Labels: bug

#112 chore: bugfixs and styling
  views/pages/budget-form.ejs
  views/pages/goals-form.ejs
  views/script/budgetCreation.js
  views/script/goalsForm.js
  views/styles/styles.css
  views/styles/styles.scss
Labels: bug, enhancement

#113 chore: Added styling changes to dash
  views/pages/budget-page.ejs
  views/pages/goals-page.ejs
  views/pages/registration-form.ejs
  views/script/budgetPage.js
  views/script/goalsPage.js
  views/styles/styles.css
  views/styles/styles.scss
Labels: bug, enhancement

#114 chore: App Name Change
  docs/layout.md
  views/pages/budget-form.ejs
  views/pages/budget-page.ejs
  views/pages/contact-page.ejs
  views/pages/goals-form.ejs
  views/pages/goals-page.ejs
  views/pages/index.ejs
  views/pages/login-form.ejs
  views/pages/registration-form.ejs
  views/pages/user-dashboard.ejs
  views/partials/footer.ejs
Labels: enhancement

#115 feat: added goal update button
  routes/user-account-routes.js
  views/pages/goals-page.ejs
  views/pages/user-dashboard.ejs
  views/script/goalsPage.js
  views/styles/styles.css
  views/styles/styles.scss
Labels: bug, enhancement
